Data_config:
  most_frequent_class: 225
  n_samples_per_class: 425
  num_classes: 230
  split_strategy: stratified
  stratify_distribution: equal
  stratify_on: Crystal system (Number)
Model_config:
  hidden_channels: 32
  in_channels: 7
  num_layers: 2
  out_channels: 64
Secondary_config:
  hidden_channels: 147
  in_channels: 192
  out_channels: 230
Train_config:
  batch_size: 16
  epochs: 1000
  learning_rate: 0.001
  max_patience: 50
  seeds:
  - 42
  - 43
  - 44
  train_time: 3600
dataset: CHILI-100K
log_dir: results_n_samples_per_class_425
model: GraphSAGE
root: dataset
save_latest_model: false
task: SpacegroupClassification
