Model_config:
  hidden_channels: 32
  in_channels: 4
  num_layers: 2
  out_channels: 3
Train_config:
  batch_size: 10
  epochs: 2
  learning_rate: 0.01
  seeds:
  - 42
  - 43
  - 44
  train_time: 3600
dataset: Simulated_rmax60_v4
log_dir: ./Results/
model: GAT
root: ./Dataset/
task: PositionRegression
