# Description: This is a test config file for the main.py
dataset: GraphNPs_sim_60
root: ./Dataset/
log_dir: ./Results/
task: NodeClassification
model: EdgeCNN
Model_config:
  num_layers: 2
  in_channels: -1
  hidden_channels: 32
  out_channels: 118
  act: relu
Train_config:
  learning_rate: 0.01
  epochs: 50
  batch_size: 32
  seed: 42
