Model_config:
  hidden_channels: 64
  in_channels: 7
  num_layers: 2
  out_channels: 64
Train_config:
  batch_size: 16
  epochs: 1000
  learning_rate: 0.01
  max_patience: 5
  seeds:
  - 42
  - 43
  - 44
  train_time: 3600
dataset: Simulated_rmax60_v4
log_dir: ./Results/
model: GAT
root: ./Dataset/
save_latest_model: false
task: xPDFRegression
